    ALTER TABLE `WeatherData` ADD IF NOT EXISTS `SerialNumber` INT NOT NULL DEFAULT '0' AFTER `CPUTemperature`;

ALTER TABLE `WeatherData` ADD IF NOT EXISTS `RSSI` FLOAT NOT NULL AFTER `SerialNumber`, ADD `SNR` FLOAT NOT NULL AFTER `RSSI`, ADD `NOISE` FLOAT NOT NULL AFTER `SNR`;



